# Generated by Django 6.0 on 2025-12-24 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jlpt_level', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], max_length=2)),
                ('order', models.PositiveIntegerField(help_text='Thứ tự bài trong level (1,2,3,...)')),
                ('title', models.CharField(help_text='VD: Bài 1: Giới thiệu bản thân', max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['jlpt_level', 'order'],
                'unique_together': {('jlpt_level', 'order')},
            },
        ),
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(blank=True, max_length=50)),
                ('hiragana', models.CharField(max_length=100)),
                ('vietnamese', models.CharField(help_text='Từ Hán–Việt / viết hoa trong UI', max_length=100)),
                ('meaning', models.TextField(help_text='Nghĩa tiếng Việt')),
                ('audio', models.FileField(blank=True, null=True, upload_to='vocabulary/audio/')),
                ('order', models.PositiveIntegerField(help_text='Thứ tự hiển thị flashcard trong bài')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='vocab.vocabularylesson')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('lesson', 'order')},
            },
        ),
        migrations.CreateModel(
            name='VocabularyExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_jp', models.TextField()),
                ('sentence_vi', models.TextField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='vocab.vocabularyword')),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_words', models.PositiveIntegerField(default=0, help_text='Số từ đã học xong trong bài')),
                ('is_completed', models.BooleanField(default=False)),
                ('last_studied_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.vocabularylesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='VocabularyFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.vocabularyword')),
            ],
            options={
                'unique_together': {('user', 'word')},
            },
        ),
        migrations.CreateModel(
            name='VocabularyWordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_learned', models.BooleanField(default=False)),
                ('last_reviewed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.vocabularyword')),
            ],
            options={
                'unique_together': {('user', 'word')},
            },
        ),
    ]
