# Generated by Django 6.0 on 2025-12-24 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], max_length=2)),
                ('order', models.PositiveIntegerField(help_text='Thứ tự bài trong level (1, 2, 3...)')),
                ('title', models.CharField(help_text='Ví dụ: 第1部 - 文体', max_length=255)),
                ('preview', models.CharField(help_text='Preview hiển thị ở danh sách: 文体, 文体, 文体', max_length=255)),
            ],
            options={
                'ordering': ['level', 'order'],
                'unique_together': {('level', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Nội dung câu hỏi đọc hiểu')),
                ('order', models.PositiveIntegerField(help_text='Thứ tự câu hỏi')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reading.readinglesson')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('lesson', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ReadingChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Nội dung đáp án', max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='reading.readingquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_count', models.PositiveIntegerField(default=0, help_text='Số câu trả lời đúng')),
                ('total_questions', models.PositiveIntegerField(help_text='Tổng số câu hỏi trong bài')),
                ('progress', models.PositiveIntegerField(default=0, help_text='Tiến độ % (0 - 100)')),
                ('status', models.CharField(choices=[('not-started', 'Not started'), ('in-progress', 'In progress'), ('completed', 'Completed')], default='not-started', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.readinglesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='ReadingText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_japanese', models.TextField(help_text='Nội dung tiếng Nhật')),
                ('content_vietnamese', models.TextField(help_text='Bản dịch tiếng Việt')),
                ('order', models.PositiveIntegerField(help_text='Thứ tự đoạn đọc trong bài')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='reading.readinglesson')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('lesson', 'order')},
            },
        ),
    ]
