# Generated by Django 6.0 on 2025-12-25 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KanjiLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.PositiveIntegerField(help_text='Số thứ tự bài học trong unit (1, 2, 3...)')),
                ('lesson_name', models.CharField(blank=True, help_text='Tên bài học (駐車場, 宿泊...)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Thứ tự sắp xếp')),
            ],
            options={
                'verbose_name': 'Kanji Lesson',
                'verbose_name_plural': 'Kanji Lessons',
                'ordering': ['unit', 'order', 'lesson_number'],
            },
        ),
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(db_index=True, help_text='Chữ kanji', max_length=1)),
                ('hiragana', models.CharField(blank=True, help_text='Đọc hiragana chính', max_length=50)),
                ('vietnamese', models.CharField(help_text='Đọc Hán Việt (VD: NHẬT, HỌC...)', max_length=50)),
                ('stroke_count', models.PositiveIntegerField(help_text='Số nét')),
                ('kunyomi', models.CharField(blank=True, help_text='Âm Kun (訓読み)', max_length=100)),
                ('onyomi', models.CharField(blank=True, help_text='Âm On (音読み)', max_length=100)),
                ('meaning', models.TextField(help_text='Nghĩa tiếng Việt')),
                ('order', models.PositiveIntegerField(default=0, help_text='Thứ tự trong bài học')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanjis', to='kanji.kanjilesson')),
            ],
            options={
                'verbose_name': 'Kanji',
                'verbose_name_plural': 'Kanjis',
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='KanjiUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], help_text='Cấp độ JLPT', max_length=2)),
                ('unit_number', models.PositiveIntegerField(help_text='Số thứ tự unit (1, 2, 3...)')),
                ('unit_name', models.CharField(help_text='Tên unit (第1週, 第2週...)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Mô tả nội dung unit')),
                ('order', models.PositiveIntegerField(default=0, help_text='Thứ tự sắp xếp')),
            ],
            options={
                'verbose_name': 'Kanji Unit',
                'verbose_name_plural': 'Kanji Units',
                'ordering': ['level', 'order', 'unit_number'],
                'unique_together': {('level', 'unit_number')},
            },
        ),
        migrations.AddField(
            model_name='kanjilesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='kanji.kanjiunit'),
        ),
        migrations.CreateModel(
            name='KanjiVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji_word', models.CharField(help_text='Từ vựng có kanji (駐車, 日本...)', max_length=50)),
                ('hiragana', models.CharField(help_text='Đọc hiragana (ちゅうしゃ)', max_length=50)),
                ('reading', models.CharField(help_text='Đọc Hán Việt (TRÚ XA)', max_length=50)),
                ('meaning', models.CharField(help_text='Nghĩa tiếng Việt', max_length=200)),
                ('example_sentence', models.TextField(blank=True, help_text='Câu ví dụ (tùy chọn)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Thứ tự từ vựng')),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='kanji.kanji')),
            ],
            options={
                'verbose_name': 'Kanji Vocabulary',
                'verbose_name_plural': 'Kanji Vocabularies',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KanjiFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanji.kanji')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanji_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kanji Favorite',
                'verbose_name_plural': 'Kanji Favorites',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'kanji')},
            },
        ),
        migrations.CreateModel(
            name='KanjiProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_learned', models.BooleanField(default=False, help_text='Đã học xong')),
                ('is_mastered', models.BooleanField(default=False, help_text='Đã thành thạo')),
                ('review_count', models.PositiveIntegerField(default=0, help_text='Số lần ôn tập')),
                ('last_reviewed_at', models.DateTimeField(auto_now=True)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanji.kanji')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanji_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kanji Progress',
                'verbose_name_plural': 'Kanji Progress',
                'unique_together': {('user', 'kanji')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='kanjilesson',
            unique_together={('unit', 'lesson_number')},
        ),
    ]
