# Generated by Django 6.0 on 2025-12-25 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JLPTQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(help_text='Số thứ tự câu hỏi (1, 2, 3...)')),
                ('instruction', models.TextField(blank=True, help_text='Hướng dẫn cho câu hỏi (tiếng Nhật)')),
                ('sentence', models.TextField(blank=True, help_text='Câu hỏi (câu văn tiếng Nhật)')),
                ('underlined_word', models.CharField(blank=True, help_text='Từ được gạch chân', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='jlpt_practice/images/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='jlpt_practice/audio/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Độ dài audio (giây)', null=True)),
                ('explanation', models.TextField(blank=True, help_text='Giải thích đáp án')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'JLPT Question',
                'verbose_name_plural': 'JLPT Questions',
                'ordering': ['section', 'question_number'],
            },
        ),
        migrations.CreateModel(
            name='JLPTSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('reading', 'Reading'), ('listening', 'Listening')], max_length=20)),
                ('title_jp', models.CharField(help_text='Tiêu đề tiếng Nhật (ví dụ: 文字・語彙)', max_length=255)),
                ('title_vn', models.CharField(help_text='Tiêu đề tiếng Việt (ví dụ: Từ vựng)', max_length=255)),
                ('order', models.PositiveIntegerField(help_text='Thứ tự section trong test')),
                ('max_score', models.PositiveIntegerField(default=60, help_text='Điểm tối đa cho section này')),
            ],
            options={
                'verbose_name': 'JLPT Section',
                'verbose_name_plural': 'JLPT Sections',
                'ordering': ['test', 'order'],
            },
        ),
        migrations.CreateModel(
            name='JLPTChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Nội dung lựa chọn', max_length=255)),
                ('order', models.PositiveIntegerField(help_text='Thứ tự (1, 2, 3, 4)')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='jlpt_practice.jlptquestion')),
            ],
            options={
                'verbose_name': 'JLPT Choice',
                'verbose_name_plural': 'JLPT Choices',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.AddField(
            model_name='jlptquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='jlpt_practice.jlptsection'),
        ),
        migrations.CreateModel(
            name='JLPTSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên sub-category (ví dụ: Cách đọc kanji)', max_length=255)),
                ('order', models.PositiveIntegerField(help_text='Thứ tự')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='jlpt_practice.jlptsection')),
            ],
            options={
                'verbose_name': 'JLPT SubSection',
                'verbose_name_plural': 'JLPT SubSections',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.AddField(
            model_name='jlptquestion',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='jlpt_practice.jlptsubsection'),
        ),
        migrations.CreateModel(
            name='JLPTTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], db_index=True, max_length=2)),
                ('order', models.PositiveIntegerField(help_text='Thứ tự đề thi (Test 1, Test 2...)')),
                ('title', models.CharField(help_text='Tên đề thi (ví dụ: Test 1)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Mô tả về đề thi')),
                ('duration_minutes', models.PositiveIntegerField(default=140, help_text='Thời gian làm bài (phút)')),
                ('total_score', models.PositiveIntegerField(default=180, help_text='Tổng điểm tối đa')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'JLPT Test',
                'verbose_name_plural': 'JLPT Tests',
                'ordering': ['level', 'order'],
                'unique_together': {('level', 'order')},
            },
        ),
        migrations.AddField(
            model_name='jlptsection',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='jlpt_practice.jlpttest'),
        ),
        migrations.CreateModel(
            name='JLPTAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted')], default='in_progress', max_length=20)),
                ('score', models.PositiveIntegerField(default=0, help_text='Tổng điểm đạt được')),
                ('total_score', models.PositiveIntegerField(default=180, help_text='Tổng điểm tối đa')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jlpt_attempts', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='jlpt_practice.jlpttest')),
            ],
            options={
                'verbose_name': 'JLPT Attempt',
                'verbose_name_plural': 'JLPT Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='JLPTAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='jlpt_practice.jlptattempt')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jlpt_practice.jlptchoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jlpt_practice.jlptquestion')),
            ],
            options={
                'verbose_name': 'JLPT Answer',
                'verbose_name_plural': 'JLPT Answers',
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='jlptquestion',
            unique_together={('section', 'question_number')},
        ),
        migrations.AlterUniqueTogether(
            name='jlptsection',
            unique_together={('test', 'section_type')},
        ),
    ]
