# Generated by Django 6.0 on 2025-12-25 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên giọng đọc (VD: あおい)', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Tên hiển thị', max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ')], max_length=10)),
                ('language', models.CharField(default='ja', help_text='Mã ngôn ngữ', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Mô tả về giọng đọc')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Voice',
                'verbose_name_plural': 'Voices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShadowingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=10)),
                ('text_input', models.TextField(blank=True, help_text='Văn bản để chuyển thành giọng nói')),
                ('image', models.ImageField(blank=True, help_text='Hình ảnh để OCR', null=True, upload_to='shadowing/images/')),
                ('speed', models.FloatField(default=1.0, help_text='Tốc độ đọc (0.5 - 2.0)')),
                ('pitch', models.IntegerField(default=0, help_text='Cao thấp giọng nói (-10 đến +10)')),
                ('audio_file', models.FileField(blank=True, help_text='File âm thanh được tạo', null=True, upload_to='shadowing/audio/')),
                ('audio_duration', models.CharField(blank=True, help_text='Độ dài audio (mm:ss)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shadowing_sessions', to=settings.AUTH_USER_MODEL)),
                ('voice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='shadowing.voice')),
            ],
            options={
                'verbose_name': 'Shadowing Session',
                'verbose_name_plural': 'Shadowing Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
