# Generated by Django 6.0 on 2025-12-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammarprogress',
            name='total_questions',
        ),
    ]
