# Generated by Django 6.0 on 2025-12-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('vocab', 'Vocabulary'), ('kanji', 'Kanji'), ('grammar', 'Grammar'), ('sentence', 'Sentence')], max_length=10)),
                ('keyword', models.CharField(db_index=True, help_text='Từ khóa tìm kiếm (kanji / kana / câu)', max_length=255)),
                ('reading', models.CharField(blank=True, help_text='Cách đọc (hiragana / katakana)', max_length=255)),
                ('meaning', models.TextField(help_text='Nghĩa tiếng Việt')),
                ('extra', models.TextField(blank=True, help_text='Ví dụ / cấu trúc / on-kun...')),
                ('jlpt_level', models.CharField(blank=True, help_text='N5–N1 (optional)', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
